name: Cloud Functions Deployment

on:
    push:
        branches:
            [main]
    pull_request:
        branches:
            [main]

jobs:
    run:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v3

            -   id: auth
                uses: google-github-actions/auth@v1
                with:
                    credentials_json: ${{ secrets.GCP_SA_KEY }}
                
            -   name: Set up Cloud SDK
                uses: google-github-actions/setup-gcloud@v1
            
            -   name: Deploying the functions
                run : |-
                    gcloud deploy functions recent_repo_card
                        --trigger-http
                        --runtime=nodejs20 
                        --region=us-central1 
                        --entry-point=card 
                        --gen2 
                        --allow-unauthenticated